version: "0.2"
ignorePaths: []
dictionaries: [project-words]
dictionaryDefinitions:
  - name: "project-words"
    path: "./project-words.txt"
    addWords: true

words: []
ignoreWords: [a]
import: []
language: "nl,en"
